// Original lines written for this app. Themes are interleaved in the daily rotation.
const THEMES = [
  {
    quotes: [
      "The day becomes clearer when you give your attention to one thing at a time.",
      "Attention is a way of saying that this moment matters.",
      "The ordinary moments are not waiting for life to begin.",
      "Make room for wonder, even on a familiar path.",
      "Notice what remains steady when the day changes around you.",
      "A pause can be the most useful part of a response.",
      "A quiet hour is not empty when you are present for it.",
      "What you notice shapes the life you remember.",
      "Look up long enough to see where you already are.",
      "One careful conversation can matter more than a crowded day.",
      "Give the person in front of you your undivided minute.",
      "The first step toward clarity is often to stop filling every silence.",
      "Some answers appear only after you have listened well.",
      "There is more to a day than its most urgent demand.",
      "Let a familiar place surprise you once in a while.",
      "You cannot attend to everything; choose what deserves you.",
      "A slow look can reveal what a hurried glance missed.",
      "Return to the present as often as you need to.",
    ],
    prompts: [
      "What deserves your full attention today?",
      "What did you notice today that you might usually miss?",
      "Where could you make room for a quieter moment?",
    ],
  },
  {
    quotes: [
      "Let the things you cannot control be lighter than the things you can.",
      "Give your energy to what is yours to do today.",
      "The mind grows quieter when it stops arguing with what has already happened.",
      "You can choose your response even when you could not choose the event.",
      "Not every burden belongs in your hands.",
      "A boundary can be a kind way to tell the truth.",
      "Spend less strength trying to command the weather; prepare your own shelter.",
      "You may not direct the whole day, but you can direct the next step.",
      "Release the argument with yesterday and use what it taught you.",
      "Your effort is yours; the outcome has more than one author.",
      "Peace grows where responsibility ends and acceptance begins.",
      "Do the work that is yours without claiming the whole result.",
      "When a plan changes, your values can remain.",
      "You do not need certainty to act with care.",
      "Choose what you can carry well, then set down the rest.",
      "Let your choices answer the part of the problem you can reach.",
      "There is freedom in naming what is beyond your control.",
      "A steady response is an achievement even on an unsteady day.",
    ],
    prompts: [
      "Which part of a current worry is actually yours to act on?",
      "What could you release today without neglecting your responsibilities?",
      "How would you like to respond if a plan changes?",
    ],
  },
  {
    quotes: [
      "Progress can be quiet and still be real.",
      "You can begin again without calling yesterday a failure.",
      "A difficult feeling may be present without making every decision.",
      "A setback can change your route without changing your direction.",
      "Rest before you are empty, and return when you are ready.",
      "Getting through a hard day is sometimes the work of the day.",
      "Courage may look like trying once more, gently.",
      "You are allowed to learn at the speed of a human life.",
      "A small return to your values still counts as a return.",
      "The path forward can begin with admitting what hurts.",
      "You have survived change before; you can meet this one step by step.",
      "Strength is not the absence of tenderness.",
      "An unfinished day can still hold something worth keeping.",
      "The next beginning does not have to resemble the last one.",
      "Ask for help before you have used every last bit of strength.",
      "It is possible to be tired and still be moving forward.",
      "Give yourself credit for the effort no one else could see.",
      "A hard chapter is part of the story, not the whole book.",
    ],
    prompts: [
      "What small sign of progress might you be overlooking?",
      "What would a gentle restart look like today?",
      "Where might support make the next step easier?",
    ],
  },
  {
    quotes: [
      "Gratitude begins by noticing what you might have walked past.",
      "Small acts of care have a way of outlasting the moment.",
      "The simple things become precious when you give them your attention.",
      "A good memory can be a place to rest for a moment.",
      "Thankfulness makes room for joy without denying difficulty.",
      "Someone's ordinary kindness may have changed your whole afternoon.",
      "Notice the help that arrived without asking to be remembered.",
      "A meal, a message, a patch of shade: enough can arrive quietly.",
      "You can be grateful for a day that was not easy.",
      "The people who made room for you deserve a place in your memory.",
      "Let today's small comforts be more than background.",
      "Appreciation grows when it is spoken aloud.",
      "What you cherish becomes easier to care for.",
      "A familiar kindness is still a gift.",
      "Remember who helped you become a little more yourself.",
      "Gratitude can sit beside longing; neither has to leave.",
      "The best parts of a day are not always the loudest.",
      "Make a little space to thank what held you up.",
    ],
    prompts: [
      "What small kindness from today would you like to remember?",
      "Who helped you recently, and what did it mean to you?",
      "What ordinary comfort are you grateful for right now?",
    ],
  },
  {
    quotes: [
      "The next kind action is often close enough to take now.",
      "A generous interpretation can change the shape of a day.",
      "Listen for what someone means, not only for what they said.",
      "A thoughtful question can be a form of care.",
      "Make it easier for the people you love to tell you the truth.",
      "Kindness is most useful when it reaches someone in time.",
      "You do not need a perfect sentence to check on a friend.",
      "Give praise while the person can still hear it.",
      "A disagreement need not erase your respect.",
      "People remember how safe it felt to be honest with you.",
      "Make room for another person's unseen day.",
      "A little patience can protect a great deal of trust.",
      "Be present for the answer after you ask how someone is.",
      "Repair begins when being right matters less than being clear.",
      "A shared silence can be company too.",
      "Offer the care you can actually sustain.",
      "Let people change without holding them to an old version of themselves.",
      "The smallest welcome can make a place feel like home.",
    ],
    prompts: [
      "Who might appreciate a thoughtful message from you today?",
      "Where could you listen more generously?",
      "Is there a small relationship repair you could begin?",
    ],
  },
  {
    quotes: [
      "You do not need to carry tomorrow before it arrives.",
      "Look for what this moment asks, rather than what the whole future demands.",
      "The measure of a day is not only what you finished, but how you lived it.",
      "An hour given freely can be more valuable than one filled completely.",
      "Leave enough space in the day to feel that you were in it.",
      "Not every minute needs to become evidence of progress.",
      "Time spent caring for someone is time well used.",
      "A slower morning can change the way you meet the afternoon.",
      "What matters can be urgent without asking you to rush.",
      "Do not spend the present rehearsing every possible future.",
      "The hours you remember are rarely the ones you optimized best.",
      "A day is large enough for work and for being alive.",
      "You can close a day without closing every open task.",
      "Give important things a place on the calendar, not only in your wishes.",
      "Some moments ask to be lived before they are understood.",
      "A season of waiting can still be a season of living.",
      "Spend an unhurried minute with something you would miss.",
      "The future is shaped by how you inhabit the days that lead to it.",
    ],
    prompts: [
      "What could you stop postponing until a less busy day?",
      "How would you like to spend one unhurried hour this week?",
      "What can wait until tomorrow without harm?",
    ],
  },
  {
    quotes: [
      "A good question can open a door that certainty keeps closed.",
      "Be willing to learn from the day you actually had.",
      "Keep what teaches you; release what only weighs you down.",
      "Curiosity turns a mistake into something more than regret.",
      "The lesson may be smaller and more useful than the grand conclusion.",
      "Ask what changed your mind, and let the answer matter.",
      "You can know more today without judging who you were yesterday.",
      "A careful observation can be worth more than a quick opinion.",
      "Let a new idea be unfamiliar before deciding whether it is wrong.",
      "Learning often starts with an honest 'I don't know.'",
      "Keep notes on what surprises you; surprise is a good teacher.",
      "A book becomes part of your life when you test an idea from it.",
      "The question you avoid may be the one that helps you grow.",
      "You do not have to agree with a lesson to examine it well.",
      "A changed mind can be evidence of attention, not weakness.",
      "Experience teaches best when you give it time to speak.",
      "Learn from the person beside you, not only the expert far away.",
      "The next useful insight may arrive disguised as confusion.",
    ],
    prompts: [
      "What surprised you recently, and what might it teach you?",
      "Is there a belief you are ready to examine more closely?",
      "What idea from a book or conversation could you try today?",
    ],
  },
  {
    quotes: [
      "It is enough to be honest about where you are and keep going.",
      "Practice meeting uncertainty with curiosity instead of fear.",
      "There is strength in choosing patience when haste is available.",
      "Bravery can begin with a truthful sentence.",
      "You may feel afraid and still do what matters.",
      "Do the kind thing even when no one will notice.",
      "A difficult conversation is easier to face than a long season of silence.",
      "Courage is often ordinary action under uncertain conditions.",
      "Choose honesty that is both clear and kind.",
      "The first attempt does not have to prove the whole journey.",
      "You can ask the question even if the answer might change your plans.",
      "Stand by a value when it costs more than a slogan.",
      "Do not confuse discomfort with a warning to stop.",
      "The brave step may be to slow down and reconsider.",
      "It takes courage to admit that you need another way.",
      "Let your actions be a little more honest than your fears.",
      "A sincere apology is a form of strength.",
      "Begin before confidence arrives; it may meet you on the way.",
    ],
    prompts: [
      "What honest step have you been putting off?",
      "Where could you act on a value despite some uncertainty?",
      "What would courage look like in an ordinary moment today?",
    ],
  },
  {
    quotes: [
      "Rest is part of a life well lived, not a reward for finishing it.",
      "Choose the next right step before trying to see the whole road.",
      "Some problems become smaller when you stop adding to them.",
      "A simpler plan can make room for a fuller life.",
      "Enough is a useful word to know when to stop.",
      "Keep a little empty space for what you cannot schedule.",
      "Not every opportunity belongs to this season.",
      "Clear one small corner and see how the room feels.",
      "You can want less without caring less.",
      "The important task often needs less noise, not more effort.",
      "A short list completed with care can be a good day.",
      "Saying no can protect a more meaningful yes.",
      "Let your routine make room for a life outside the routine.",
      "There is relief in doing one thing well enough.",
      "A quiet evening does not need to justify itself.",
      "Make space before deciding what to fill it with.",
      "The easiest thing to remove may be the thing you never chose.",
      "A little less hurry can reveal a better direction.",
    ],
    prompts: [
      "What could you simplify without losing what matters?",
      "Where do you need rest before another task?",
      "What deserves a clear yes, and what can receive a no?",
    ],
  },
  {
    quotes: [
      "A calmer life is built one deliberate choice at a time.",
      "What you practice in small moments becomes how you meet the large ones.",
      "You can hold an ambition gently and still move toward it.",
      "What matters most deserves some of your unhurried attention.",
      "A meaningful life is made in ordinary decisions.",
      "Let your habits make your values visible.",
      "You can change direction without losing the purpose behind the journey.",
      "Do not wait for a grand moment to act like the person you hope to be.",
      "A clear reason helps a small effort endure.",
      "The work that matters may grow slowly and still be worth doing.",
      "Let your definition of success leave room for people and peace.",
      "Choose a goal you can pursue without abandoning yourself.",
      "A life of meaning does not need to look impressive from a distance.",
      "Return to what you value when the noise gets loud.",
      "The way you do a small task can express a larger belief.",
      "Take care that the path to your goal is one you can live with.",
      "Purpose is easier to find in a practice than in a proclamation.",
      "Let your days reflect the things you say you care about.",
    ],
    prompts: [
      "What value would you like one choice today to express?",
      "Which small habit supports the life you want to live?",
      "Is a current goal still serving what matters to you?",
    ],
  },
] as const;

export const DAILY_QUOTE_COUNT = THEMES.reduce(
  (total, theme) => total + theme.quotes.length,
  0,
);

const DAY_MS = 86_400_000;
const TIME_ZONE = "Asia/Singapore";

export function getDailyQuote(now: Date) {
  const parts = new Intl.DateTimeFormat("en-GB", {
    timeZone: TIME_ZONE,
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
  }).formatToParts(now);
  const value = (type: string) =>
    Number(parts.find((part) => part.type === type)?.value);
  const dayNumber = Math.floor(
    Date.UTC(value("year"), value("month") - 1, value("day")) / DAY_MS,
  );
  const index =
    ((dayNumber % DAILY_QUOTE_COUNT) + DAILY_QUOTE_COUNT) % DAILY_QUOTE_COUNT;
  const theme = THEMES[index % THEMES.length];
  const round = Math.floor(index / THEMES.length);

  return {
    text: theme.quotes[round],
    prompt: theme.prompts[round % theme.prompts.length],
    date: new Intl.DateTimeFormat("en-SG", {
      timeZone: TIME_ZONE,
      weekday: "long",
      day: "numeric",
      month: "long",
      year: "numeric",
    }).format(now),
  };
}
