import { singaporeDayNumber } from "./daily-quote";

// Original mindfulness lines written for this app. Each appears once per 180-day cycle.
const MINDFULNESS_QUOTES = [
  // Breath and pause
  "One unhurried breath can give the day a softer beginning.",
  "The breath asks for no achievement; it only asks to be noticed.",
  "Pause long enough to feel where your feet meet the ground.",
  "A moment of stillness belongs inside a busy life too.",
  "Let the next breath arrive before you decide what comes next.",
  "You can begin again in the space between two breaths.",
  "Notice the exhale; it is a small lesson in letting go.",
  "A pause is not lost time when it helps you return to yourself.",
  "The body is here even when the mind has gone ahead.",
  "Give yourself one breath without a task attached to it.",
  "The day can wait for the length of an exhale.",
  "Slow your breathing enough to hear what hurry has covered.",
  "A quiet breath is a place to begin, not a place to hide.",
  "When you feel scattered, start with the simple fact that you are breathing.",
  "The next inhale does not need to repair the whole day.",
  "Make a little room between the feeling and the reply.",
  "You can pause without falling behind your own life.",
  "Breathe as though this minute is worth being present for.",
  "One mindful breath will not change everything, and it can change this moment.",
  "Let your shoulders learn that the present is enough to hold.",
  "The first sign of calm may be noticing that you need it.",
  "Return to the breath whenever you remember; remembering is the practice.",
  "A pause lets your attention catch up with your actions.",
  "Inhale what is here; exhale the need to rush past it.",
  "The body often knows you are tired before your plans do.",
  "Stillness can be brief and still be real.",
  "Let a single breath mark the end of one thing and the start of another.",
  "Notice how the air enters without asking you to be ready.",
  "You are allowed to take a breath before answering.",
  "A slower breath can make room for a wiser next step.",

  // Senses and surroundings
  "The light on an ordinary wall is part of this day too.",
  "Look closely; the familiar world is never quite the same twice.",
  "The sound nearest to you can bring you back to now.",
  "Feel the cup in your hands before thinking of the next thing.",
  "A small detail noticed is a moment fully lived.",
  "Let the weather be weather before making it a problem.",
  "Notice the ground holding you without asking for your attention.",
  "There is a whole morning in the first patch of light.",
  "The room you are in deserves a moment of your presence.",
  "Listen once without naming every sound.",
  "A familiar walk can become new when you stop rehearsing the destination.",
  "The warmth of water is worth feeling while it lasts.",
  "Let your eyes rest on something that asks nothing of you.",
  "The world offers more than the part that fits on a screen.",
  "Notice one color you did not expect to see today.",
  "Even a crowded street has a rhythm you can hear.",
  "The smell of a meal can be an invitation to arrive.",
  "Touch the table; remember that you are here, not only in your thoughts.",
  "A breeze is brief, and that is reason enough to feel it.",
  "Your senses can lead you home from a distant worry.",
  "Look at the sky before you decide the day is small.",
  "The present has texture, temperature, and sound.",
  "Let the first sip be something you actually taste.",
  "The way shadows move can tell you that time is passing gently.",
  "See the person beside you before returning to your list.",
  "A quiet corner can hold more life than a crowded thought.",
  "Notice what changes when you listen past the loudest sound.",
  "The world becomes less abstract when you feel the ground beneath you.",
  "Let one ordinary sight have your full attention.",
  "You do not need a special place to be present.",

  // Thoughts and attention
  "A thought can pass through without becoming your next action.",
  "Notice where your attention goes; you can invite it back.",
  "The mind makes stories quickly; give reality a chance to speak.",
  "You can hear a thought without agreeing to follow it.",
  "Attention returns in small steps, not in one perfect leap.",
  "When your mind wanders, the return is part of the moment.",
  "A worry is easier to hold when you name it as a worry.",
  "Let a passing thought be a visitor, not the owner of the room.",
  "You can notice distraction without turning it into a failure.",
  "The present does not demand a perfectly quiet mind.",
  "Thoughts move; your awareness can remain.",
  "An unfinished thought can wait while you finish this breath.",
  "Ask whether the story in your mind is the whole story.",
  "You can be curious about a thought instead of trapped inside it.",
  "Attention is renewed each time you choose where to place it.",
  "Do not mistake the loudest thought for the truest one.",
  "Notice the space around a thought before filling it with another.",
  "A busy mind can still meet one quiet moment.",
  "Let the next thought come without chasing the last one.",
  "The mind may travel; the breath can show it the way back.",
  "You need not solve every thought that appears.",
  "A thought is an event in the present, not a verdict on the future.",
  "Gently returning is a skill built by returning again.",
  "Give one conversation more attention than your inner rehearsal.",
  "Notice when planning has become a way of leaving this moment.",
  "You can put down a thought without proving it wrong.",
  "The next moment is clearer when you stop arguing with the last one.",
  "Listen to your mind with interest, not automatic obedience.",
  "One thing at a time is enough to be here.",
  "Awareness begins where automatic reaction pauses.",

  // Feelings and acceptance
  "A feeling can be real without being permanent.",
  "Make room for what you feel before asking it to change.",
  "You can notice discomfort without making an enemy of it.",
  "The first kindness may be admitting that this is hard.",
  "Let a feeling have a name and a little space.",
  "Calm is not a requirement for being present.",
  "Some days mindfulness sounds like: this is what is here.",
  "You do not have to like this moment to meet it honestly.",
  "Hold a difficult feeling gently enough to learn its shape.",
  "A heavy mood is part of the weather, not the whole sky.",
  "Notice what softens when you stop resisting the fact of a feeling.",
  "You can care for yourself without needing to feel better first.",
  "Let joy be felt before you explain why it arrived.",
  "Sadness can sit beside an ordinary task without taking it over.",
  "The body may tell the truth in a tightened jaw or a tired hand.",
  "A feeling deserves attention, not necessarily a command.",
  "Meet impatience with curiosity before it chooses your words.",
  "You can be anxious and still feel the chair beneath you.",
  "Allow delight to last longer than your urge to move on.",
  "Noticing anger is the beginning of choosing what to do with it.",
  "There is room in this moment for more than one feeling.",
  "Be with the feeling for a breath before searching for its lesson.",
  "Acceptance begins with seeing clearly what is already here.",
  "You can give a difficult moment care without giving it the whole day.",
  "A tender response to yourself is also a mindful one.",
  "Feelings change more freely when they are allowed to be noticed.",
  "The present can hold uncertainty without asking you to resolve it now.",
  "When you name what hurts, you make room to tend to it.",
  "A pleasant moment needs no reason to be welcomed.",
  "Let today be known before deciding what it should have been.",

  // Everyday practice
  "Wash one dish while you are washing it.",
  "The walk between tasks is still part of your life.",
  "Let your hands finish this work before your mind starts the next.",
  "An ordinary chore can anchor an unordinary mind.",
  "Close one tab in your mind by opening your eyes to the room.",
  "Eat a bite slowly enough to know it was there.",
  "Notice the beginning and ending of a small task.",
  "Waiting can be a moment to inhabit, not only a delay to endure.",
  "Let the doorway remind you to arrive where you are going.",
  "A routine becomes less automatic when you give it one curious glance.",
  "The pause before sending a message can be part of the message.",
  "Walk at a pace that lets you notice your own steps.",
  "Even folding laundry can be a way to return to the present.",
  "Before opening the next screen, notice why you reached for it.",
  "Give your first minute of rest to rest itself.",
  "The next small action is enough to practice being here.",
  "Let the sound of a door closing mark a new moment.",
  "A meal is more than the time between two tasks.",
  "You can make tea without making a plan at the same time.",
  "Pause before you hurry through something you chose to do.",
  "The space between appointments belongs to your life as well.",
  "A small task done attentively can feel less like a blur.",
  "Notice when your body asks to stand, stretch, or rest.",
  "Put both feet on the floor before the next decision.",
  "The moment you return to a task is a fresh beginning.",
  "Let the first few steps outside belong to the outdoors.",
  "A minute without a screen can still be full.",
  "Give the last task of the day a clear ending.",
  "You can travel a familiar route without leaving yourself behind.",
  "Presence is practiced in ordinary minutes, not saved for special ones.",

  // Connection and compassion
  "Listen to the pause after someone speaks.",
  "Let another person's words arrive before preparing your reply.",
  "A conversation changes when you are there for all of it.",
  "Notice the face behind the question.",
  "Your attention can be a quiet form of kindness.",
  "See the person, not only the part they play in your day.",
  "A gentle tone can begin with one breath.",
  "Give a loved one a moment free from your next task.",
  "You can be present with someone without fixing their feeling.",
  "Listen for what is said softly, not only what is said often.",
  "Compassion starts by noticing that someone else is here too.",
  "The person in front of you is not the story you rehearsed about them.",
  "Let a shared silence be enough for a moment.",
  "Meet yourself with the patience you would offer a friend.",
  "A mindful apology begins by listening to the hurt.",
  "Notice when a hurried answer would miss the real question.",
  "Presence is a gift that cannot be postponed and still be the same gift.",
  "You can hold your own needs and still see another person's.",
  "Before judging, remember that you see only this moment of their day.",
  "Listen with your whole attention for one honest minute.",
  "A kind response grows in the space before a quick reaction.",
  "The person beside you deserves more than your remaining attention.",
  "Be curious about the feeling beneath the words.",
  "Let gratitude for someone be felt while they are near.",
  "An attentive hello can change the shape of an ordinary day.",
  "Notice how your body feels when you truly listen.",
  "Offer yourself a pause before offering anyone an answer.",
  "You can make room for another view without losing your own.",
  "The warmth in a conversation is worth noticing while it is happening.",
  "Being here together is already part of what matters.",
] as const;

export const MINDFULNESS_QUOTE_COUNT = MINDFULNESS_QUOTES.length;

export function getMindfulnessQuote(now: Date) {
  const dayNumber = singaporeDayNumber(now);
  const index =
    ((dayNumber % MINDFULNESS_QUOTE_COUNT) + MINDFULNESS_QUOTE_COUNT) %
    MINDFULNESS_QUOTE_COUNT;
  return MINDFULNESS_QUOTES[index];
}
